name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check that secret is defined
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
            echo "❌ RENDER_DEPLOY_HOOK is NOT set"
            exit 1
          else
            echo "✅ RENDER_DEPLOY_HOOK is set"
          fi

      - name: Trigger Render Deploy Hook
        run: |
          echo "Deploying to Render..."
          curl $RENDER_DEPLOY_HOOK

